name: PoolControl Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    env:
      Solution_Name: PoolControl.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    - name: Execute test programs
      if: matrix.configuration == 'Release'
      run: ./Tests/Run-All.ps1

    - name: Publish the application
      run: dotnet publish PoolControl.csproj --configuration $env:Configuration --no-restore --output artifacts/publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PoolControl-${{ matrix.configuration }}
        path: artifacts/publish/
        if-no-files-found: error
